# Generated by Django 5.1.6 on 2025-05-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente_projeto_tarefa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
